---
#############################
- hosts: cluster_node_manager
  tasks:
    - name: Manager - remove stack
      ansible.builtin.command: "docker stack rm {{db['docker_stack_name']}}"
      tags: tag_prepare
      ignore_errors: true

    - name: Manager - remove network
      ansible.builtin.command: "docker network rm {{db['network_name']}}"
      tags: tag_prepare
      ignore_errors: true

- hosts: cluster_node_workers
  tasks:
    - name: Workers - Leave cluster
      ansible.builtin.command: "docker swarm leave"
      tags: tag_prepare
      ignore_errors: true


- hosts: cluster_node_manager
  tasks:
    - name: Manager - Leave cluster
      ansible.builtin.command: "docker swarm leave --force"
      tags: tag_prepare
      ignore_errors: true

###############################
- hosts: cluster_node_manager:cluster_node_workers
  tasks:
    - name: Restore files, change parameters
      block:
        - name: Restore files
          ansible.builtin.copy:
            src: "{{ item.file_path }}/{{ item.file_name }}.backup"
            dest: "{{ item.file_path }}/{{ item.file_name }}"
          loop: "{{ configs }}"

        - name: Change params
          ansible.builtin.replace:
            path: "{{ item.0.file_path }}/{{ item.0.file_name }}"
            regexp: "{{ item.1.regex }}"
            replace: "{{ item.1.replace }}"
          with_subelements:
            - "{{ configs }}"
            - params
      tags: tag_regex_files

###############################

- hosts: cluster_node_manager
  tasks:
    - name: Restore files, change parameters
      block:
        - name: Create docker compose
          ansible.builtin.command: "python3 create_docker_compose.py {{cluster_size}} {{scale}} {{mongo_catalog}}"
          args:
            chdir: "{{docker_compose_path}}"

      tags: tag_files

###############################

- hosts: cluster_node_manager
  tasks:
    - name: Init docker swarm node manager
      block:
        - name: Init swarm
          ansible.builtin.command:  docker swarm init

        - name: Register swarm worker token
          ansible.builtin.command: docker swarm join-token -q worker
          register: cluster_token
      tags: tag_init_swarm


- hosts: cluster_node_workers
  tasks:
    - name: Init docker swarm workers
      block:
        - name: Init swarm workers
          ansible.builtin.command:  "docker swarm join --token {{ hostvars[cluster['node_manager']]['cluster_token'].stdout }} {{cluster['node_manager']}}:2377"
      tags: tag_init_swarm

###############################

- hosts: cluster_node_manager
  tasks:
    - name: Create docker network
      ansible.builtin.command: "docker network create -d overlay {{ db['network_name'] }}"
      tags: tag_deploy_stack
      ignore_errors: true

    - name: Docker stack up
      ansible.builtin.command: "docker stack deploy -c {{docker_compose_path}}/docker-compose.yaml {{db['docker_stack_name']}}"
      tags: tag_deploy_stack

    - name: Wait for containers
      pause:
        seconds: 15
      tags: tag_deploy_stack


- hosts: cluster_node_manager
  tasks:
    - name: Wait for config server init
      pause:
        seconds: 15
      tags: tag_deploy_stack

    - name: Get router container id
      ansible.builtin.command: "docker ps -q --filter name={{db['docker_stack_name']}}_router* "
      register: router_id
      tags: tag_deploy_stack

    - name: Init router
      ansible.builtin.command: "docker exec {{router_id.stdout}} sh -c 'mongo < /scripts/init-script'"
      register: result
      until: result.stdout.find("failed") == -1
      retries: 5
      delay: 10
      tags: tag_deploy_stack


    - name: Wait for containers
      pause:
        seconds: 120
      tags: tag_deploy_stack


